name: Build Docker image, push to the registry and deploy applicaiton
on:
  push:
    branches:
      - 'main'
    tags:
      - '*-release'

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - name: Install Go 1.16.3
        uses: actions/setup-go@v2
        with:
         go-version: '1.16.3'
        
      - name: Install Go Linters
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.26.0
      
      - name: Run Go linter
        run: golangci-lint run hi-go/hello.go
        
        